import React from 'react';
import { Container, Row, Col, Image } from "react-bootstrap";
import Breadcrumbs from "../components/Breadcrumbs";
import { Helmet } from 'react-helmet';

const TermsOfServices = () => {
  return (
    <>
          <Helmet>
            <title>Terms of Service | ERP4Dentist</title>
            <meta name="description" content="Understand the ERP4Dentist Terms of Service for clear policies, service conditions, and responsibilities to help you use our software confidently." />
            <meta name="robots" content="index, follow" />
          </Helmet>
        <Container>
            <Breadcrumbs />
         </Container>
    <div className='section-wrap'>
        <Container className='terms'>
            <h1>Terms of Services</h1>
            <p>This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (intermediaries’ guidelines) Rules, 2011, which require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of this website.</p>
            <h2>End User License Agreement</h2>
            <p>ERP4 Dentist website is product of BLeap Digital Marketing Agency Pvt. Ltd., a technology firm with office at 46/97, Ground Floor, Poes, Varadharajapuram Main Road, Teynampet, Chennai-600018, Tamil Nadu, India, hereinafter referred to as "Company" By accessing the website (Hereafter referred to as website), installing or using this website or any portion thereof, you shall be deemed to have contracted with ERP4 Dentist and have agreed to be bound by the Terms of Services herein contained, including the various Policies incorporated by reference in the Agreement.</p>
            <h2>Use of Application:</h2>
            <ul>
                <li>The Company grants you the non-exclusive, non-transferable, limited rights & licence to install and use this application solely and exclusively for your personal use.</li>
                <li>You agree that you are solely responsible for (The company has no responsibility to you or any third party for) your use of the application, any breach of your obligations under the T&C and the consequences (any loss or damage) of any such breach.</li>
                <li>You agree that you will be responsible for usage & payment of charges related to data and voice or phone based on your mobile plan with your carrier.</li>	
            </ul>
            <h2>Proprietary Rights:</h2>
            <p>You acknowledge that the website contains proprietary and confidential information that is protected by applicable intellectual property and other laws. The company and third parties own all rights, title and interest in and to the application and content, excluding content provided by you that may be presented or accessed through the application, including without limitation, all intellectual Property rights therein and thereto. "intellectual Property Rights" means any and all the rights existing from time to time under patent law, copyright law, trademark law, unfair competition law and any other and all the proprietary rights and any and all applications, renewal, extension and restoration thereof, now or hereafter in force and effect worldwide. You agree that you will not, and will not allow any third party to, (i) copy, sell, license, distribute, transfer, modify, adapt, translate, prepare derivative works from, or otherwise attempt to derive source code from the application or content that may be presented or accessed through the application for any purpose unless permitted. (ii) Take any action to circumvent or defeat the security or content usage rules provided, deployed or enforced by any functionality. (iii) Use the application to access, copy, transfer or retransmit content in violation of any law or third-party rights or (iv) remove, obscure or alter The Company's or any other Third party's copyright notices, trademarks or proprietary rights notices affixed or contained through or within the Application.</p>
            <h2>Company Terms of Services & Privacy Policy:</h2>
            <p>The Company's privacy policy explains how the company treats your information and protects your privacy when you use the application. You agree to the use of your data in accordance with the company's privacy policies.</p>
            <p>The Company reserves the right to anonymously track and report a user's activities inside the app.</p>
            <p>You understand the need to protect the privacy of patient data. You understand the importance of password protecting the device as well as this application by using or procuring features available in the device or from other apps, vendors or software in the Marketplace. Moreover, before discarding the device, it is your responsibility to eliminate any sensitive data from the device, internal or external memory, or from wherever you have stored it.</p>
            <h2>Export Restriction:</h2>
            <p>The Application may be subject to export controls or restrictions by any countries or Territories. You agree to comply with all applicable International export laws and regulations on destinations, end users and end Use.</p>
            <h2>Termination:</h2>
            <p>These Terms and Conditions will continue to apply until terminated by either you or the Company as set forth below. You may terminate the Terms and Conditions by permanently deleting the Application. Your rights automatically & immediately terminate without notice from the Company or any third party if you fail to comply with any provision of these Terms and Conditions. In such an event, you must immediately delete the application.</p>
            <h2>Indemnity:</h2>
            <p>To the maximum extent permitted by law, you agree to defend, indemnify and hold harmless The company and its affiliates and their respective directors, officers, employee and agents from and against any and all claims, actions, suits or proceedings as well as any and all losses, liabilities, damages, costs and expenses (Including reasonable Judiciary fees) arising out of or accruing from your use of the application or your violation of Terms and Conditions.</p>
            <h2>Disclaimer of Warranties:</h2>
            <p>You expressly understand and agree that your use of the application is at your sole discretion and risk and that the application is provided as is and as available without warranty of any kind.</p>
            <p>You are solely responsible for any damage to your mobile/computer device or other device or loss of data that results from such use.</p>
            <p>The company further expressly disclaims all warranties and conditions of any kind, whether express or implied, including but not limited to implied warranties and conditions of merchantability, fitness for a particular purpose and non-infringement with respect to the application.</p>
            <h2>Miscellaneous:</h2>
            <p>These Terms & Conditions constitute the entire agreement between you and the Company relating to the application and govern your use of the application and completely replace any prior or contemporaneous agreements between you and the Company regarding the application.</p>
            <p>The failure of the Company to exercise or enforce any rights or provision of these terms and conditions doesn't constitute a waiver of such rights or provision, which will still be available to the Company.</p>
            <p>If any court of law having the jurisdiction to decide on this matter rules that any provision of these Terms and Conditions is invalid, then that provision will be removed from the Terms and Conditions without affecting the rest of the Terms and Conditions. The Remaining provisions of these Terms and Conditions will continue to be valid and enforceable.</p>
            <p>The rights granted in these Terms and Conditions may not be assigned or transferred by either you or The Company without the prior written approval of the other Party. Neither you nor the Company is permitted to delegate their responsibilities or obligations under these Terms and conditions without prior written approval of the other Party.</p>
            <p>These Terms and Conditions and your relationship with the Company under these Terms and Conditions will be governed by the laws of the Indian judiciary system without regard to its conflict-of-laws provisions. You and the Company agree to submit to the exclusive jurisdiction of the courts located in Chennai to resolve any legal matter arising from these Terms and Conditions.</p>

         </Container>
    </div>

    </>
  );
};

export default TermsOfServices;